

// Sample Data Store
let events = [
    { id: 1, title: "Future of AI Summit", date: "2024-10-24", time: "10:00 AM", venue: "Main Auditorium", category: "Tech", capacity: 200, registered: 45, desc: "AI summit with industry experts" },
    { id: 2, title: "Global Rhythm Fest", date: "2024-11-02", time: "5:30 PM", venue: "Open Grounds", category: "Cultural", capacity: 500, registered: 128, desc: "Music fest" },
    { id: 3, title: "UX Design Workshop", date: "2024-10-28", time: "2:00 PM", venue: "Design Lab", category: "Workshop", capacity: 50, registered: 32, desc: "Figma workshop" }
];
let registrations = [
    { id: 1, student: "Gaurab Sharma", eventId: 1, eventTitle: "Future of AI Summit", regDate: "2024-10-01", status: "Confirmed" },
    { id: 2, student: "Priya Karki", eventId: 2, eventTitle: "Global Rhythm Fest", regDate: "2024-10-05", status: "Confirmed" },
    { id: 3, student: "Rahul Thapa", eventId: 1, eventTitle: "Future of AI Summit", regDate: "2024-10-02", status: "Confirmed" },
    { id: 4, student: "Sita Maharjan", eventId: 3, eventTitle: "UX Design Workshop", regDate: "2024-10-10", status: "Confirmed" }
];
let venues = [
    { id: 1, name: "Main Auditorium", capacity: 300, location: "Block A", facilities: "Projector, Sound System" },
    { id: 2, name: "Design Lab", capacity: 60, location: "Block C 3rd Floor", facilities: "Mac Stations, Whiteboard" },
    { id: 3, name: "Open Grounds", capacity: 1000, location: "Central Campus", facilities: "Stage, Lights" }
];
let nextEventId = 4, nextRegId = 5, nextVenueId = 4;

function showToast(msg, type = "success") { const toast = document.getElementById("toast"); toast.textContent = msg; toast.className = `toast show ${type}`; setTimeout(() => toast.classList.remove("show"), 3000); }
function showAdminPage(page) { document.querySelectorAll(".admin-page").forEach(p => p.classList.remove("active")); document.getElementById(`page-${page}`).classList.add("active"); document.querySelectorAll(".nav-btn").forEach(btn => btn.classList.remove("active")); document.getElementById(`nav-${page}`).classList.add("active"); renderAll(); }
function renderAll() { renderStats(); renderEventsTable(); renderRecentEvents(); renderRegistrations(); renderVenuesTable(); }
function renderStats() { document.getElementById("totalEvents").innerText = events.length; document.getElementById("totalRegistrations").innerText = registrations.length; const upcoming = events.filter(e => new Date(e.date) >= new Date()).length; document.getElementById("upcomingEvents").innerText = upcoming; document.getElementById("totalVenues").innerText = venues.length; }
function renderEventsTable() { const tbody = document.getElementById("eventsTableBody"); if (!tbody) return; tbody.innerHTML = events.map(e => `<tr><td><strong>${e.title}</strong></td><td>${e.date}</td><td>${e.time}</td><td>${e.venue}</td><td><span class="badge badge-${e.category.toLowerCase()}">${e.category}</span></td><td>${e.registered}/${e.capacity}</td><td>${e.registered}</td><td class="action-icons"><i class="fa-regular fa-pen-to-square" onclick="editEvent(${e.id})"></i> <i class="fa-solid fa-trash-alt" onclick="deleteEvent(${e.id})"></i></td></tr>`).join(""); }
function renderRecentEvents() { const tbody = document.getElementById("recentEventsBody"); if (!tbody) return; const recent = [...events].slice(0, 3); tbody.innerHTML = recent.map(e => `<tr><td>${e.title}</td><td>${e.date}</td><td>${e.category}</td><td>${e.registered}</td></tr>`).join(""); }
function renderRegistrations() { const tbody = document.getElementById("registrationsTableBody"); if (!tbody) return; const search = document.getElementById("searchReg")?.value.toLowerCase() || ""; const filtered = registrations.filter(r => r.student.toLowerCase().includes(search) || r.eventTitle.toLowerCase().includes(search)); tbody.innerHTML = filtered.map(r => `<tr><td>${r.student}</td><td>${r.eventTitle}</td><td>${r.regDate}</td><td><span class="badge" style="background:#d1fae5; color:#065f46;">${r.status}</span></td><td><button class="btn-danger" onclick="cancelRegistration(${r.id})"><i class="fa-solid fa-xmark"></i> Cancel</button></td></tr>`).join(""); }
function renderVenuesTable() { const tbody = document.getElementById("venuesTableBody"); if (!tbody) return; tbody.innerHTML = venues.map(v => `<tr><td><strong>${v.name}</strong></td><td>${v.capacity}</td><td>${v.location}</td><td>${v.facilities || "-"}</td><td class="action-icons"><i class="fa-regular fa-pen-to-square" onclick="editVenue(${v.id})"></i> <i class="fa-solid fa-trash-alt" onclick="deleteVenue(${v.id})"></i></td></tr>`).join(""); }
function openEventModal(ev = null) { document.getElementById("eventModal").classList.add("active"); if (ev) { document.getElementById("eventId").value = ev.id; document.getElementById("eventTitle").value = ev.title; document.getElementById("eventDate").value = ev.date; document.getElementById("eventTime").value = ev.time; document.getElementById("eventVenue").value = ev.venue; document.getElementById("eventCategory").value = ev.category; document.getElementById("eventCapacity").value = ev.capacity; document.getElementById("eventDesc").value = ev.desc || ""; } else { document.getElementById("eventForm").reset(); document.getElementById("eventId").value = ""; } }
function closeEventModal() { document.getElementById("eventModal").classList.remove("active"); }
function editEvent(id) { const ev = events.find(e => e.id === id); if (ev) openEventModal(ev); }
function deleteEvent(id) { if (confirm("Delete this event? Registrations will also be removed.")) { events = events.filter(e => e.id !== id); registrations = registrations.filter(r => r.eventId !== id); showToast("Event deleted", "error"); renderAll(); } }
document.getElementById("eventForm")?.addEventListener("submit", (e) => { e.preventDefault(); const id = document.getElementById("eventId").value; const newEvent = { id: id ? parseInt(id) : nextEventId++, title: document.getElementById("eventTitle").value, date: document.getElementById("eventDate").value, time: document.getElementById("eventTime").value, venue: document.getElementById("eventVenue").value, category: document.getElementById("eventCategory").value, capacity: parseInt(document.getElementById("eventCapacity").value), registered: 0, desc: document.getElementById("eventDesc").value }; if (id) { const index = events.findIndex(ev => ev.id === parseInt(id)); if (index !== -1) { newEvent.registered = events[index].registered; events[index] = newEvent; showToast("Event updated", "success"); } } else { events.push(newEvent); showToast("Event created", "success"); } closeEventModal(); renderAll(); });
function cancelRegistration(regId) { if (confirm("Cancel this registration?")) { const reg = registrations.find(r => r.id === regId); if (reg) { const ev = events.find(e => e.id === reg.eventId); if (ev && ev.registered > 0) ev.registered--; registrations = registrations.filter(r => r.id !== regId); showToast("Registration cancelled", "error"); renderAll(); } } }
function openVenueModal(ven = null) { document.getElementById("venueModal").classList.add("active"); if (ven) { document.getElementById("venueId").value = ven.id; document.getElementById("venueName").value = ven.name; document.getElementById("venueCapacity").value = ven.capacity; document.getElementById("venueLocation").value = ven.location; document.getElementById("venueFacilities").value = ven.facilities || ""; } else { document.getElementById("venueForm").reset(); document.getElementById("venueId").value = ""; } }
function closeVenueModal() { document.getElementById("venueModal").classList.remove("active"); }
function editVenue(id) { const ven = venues.find(v => v.id === id); if (ven) openVenueModal(ven); }
function deleteVenue(id) { if (confirm("Delete this venue?")) { venues = venues.filter(v => v.id !== id); showToast("Venue deleted", "error"); renderAll(); } }
document.getElementById("venueForm")?.addEventListener("submit", (e) => { e.preventDefault(); const id = document.getElementById("venueId").value; const newVenue = { id: id ? parseInt(id) : nextVenueId++, name: document.getElementById("venueName").value, capacity: parseInt(document.getElementById("venueCapacity").value), location: document.getElementById("venueLocation").value, facilities: document.getElementById("venueFacilities").value }; if (id) { const index = venues.findIndex(v => v.id === parseInt(id)); if (index !== -1) venues[index] = newVenue; showToast("Venue updated", "success"); } else { venues.push(newVenue); showToast("Venue added", "success"); } closeVenueModal(); renderAll(); });
document.getElementById("searchReg")?.addEventListener("input", () => renderRegistrations());
renderAll();
